config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :flats
root to: 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat.update(flat_params)
    redirect_to flats_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
   <div class="container mt-3">
    <div class="row">
      <div class="col-12">
        <h1>All our Flats</h1>
      </div>
    </div>

  <div class="row">
    <div class="col">
      <p>You searched for <strong></strong>. We found 3 flats out of our 3 on our website.</p>
    </div>
  </div>
<div class="big-div">
    <div class ="row">
      <div class=col-4>
      <% @flats.each do |flat|  %>
        <div class="flat-card">
          <div class="flat-card-content">
            <div class="flat-card-title">
          <h4><%= link_to flat.name, flat_path(flat)%></h4>
            </div>
            <div>
          <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex">
                <i class="fas fa-users"></i><span>  3</span>
              </div>
              <div class="flex ml-3">
                <i class="fas fa-euro-sign"></i>  75
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <a href="/flats/2197">More info</a>
            <a href="#" class="ml-3 text-warning">Edit</a>
            <a href="#" class="ml-3 text-danger">Remove</a>
          </div>
        </div>
      </div>
        <% end %>
      </div>
    </div>
    </div>
  </div>

app/views/flats/new.html.erb
<div class="add-flat">
<h1>Add a new Flat</h1>
</div>

<div class="form-container">
<%= form_for(@flat) do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form-group">
  <%= f.label :address %>
  <%= f.text_field :address %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<div class="form-group">
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
</div>

<div class="form-group">
  <%= f.label :number_of_guests %>
  <%= f.number_field :number_of_guests %>
</div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>

<%= link_to 'Back to Flats', flats_path  %>

app/views/flats/show.html.erb
<div class="container">

  <div class="map">
  </div>

  <div class="litte-cards card">
    <ul>
    <h2><li><em><%= @flat.name %></em></li></h2>
      <li> <%= @flat.address %></li>
        <li>  <%= @flat.description %></li>
        <li><%= @flat.price_per_night %></li>
        <li><%= @flat.number_of_guests %></li>
      </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <div class="btn btn-outline-primary my-2 my-sm-0 ml-2"> <%=link_to 'Add', new_flat_path%></div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>